const db = {
	"CO": {
		"CO_0000": {
			"name": "Cooler Fan - Led(Azul) 120mm Eox Dual-Led",
			"price": 28.79,
			"discount": [2,5,10],
			"image": "CO_0000.png",
			"description": "Ventilador com 11 lâminas promove maximização do fluxo de ar. Possui iluminação com 15 LEDS proporcionando design moderno ao seu computador. Silenciosos e eficientes 1200RPM de força para ventilação e fluxo de ar de 44CFM. Mais organização com abertura na base dos pinos para a passagem de fios",
			"characteristics": [
				"Cooler com 15 LEDs",
				"Voltagem de 12V",
				"Corrente: 0.20A",
				"Fluxo de ar: 44CFM",
				"Velocidade: 1200 RPM (+/'10%)",
				"Nível de ruído de 21dB",
				"Conexão: 3 pinos (placa-mãe) e 4 pinos (fonte)",
				"Pads acolchoados na base dos pinos",
				"Tipo de rolamento: hidráulico",
				"Ventilador com 13 lâminas",
				"Dimensões: 120 x 120 x 25mm",
			],
			"SPdQ": false,
		},
		"CO_0001": {
			"name": "Cpu Cooler Rgb - Gamemax Gamma 200 Rainbow, 125mm",
			"price": 81.35,
			"discount": [7,0,12],
			"image": "CO_0001.png",
			"description": "Possui sistema de iluminação no padrão Rainbow com design Único<br/>Air Cooler com ótimo fluxo de ar para refrigeração de CPU com face virada para baixo<br/>Área de contato direto em cobre<br/><br/>Efeito de Luz Rainbow (não é possível alterar as cores, são trocadas aleatoriamente no sistema arco-íris)",
			"characteristics": [
				"Dimensões: 127 x 127 x 82mm (LxPxA)",
				"Dimensão do Fan: 125 x 125 x 25mm (LxPxA)",
				"Velocidade do Fan: 1800±10%RPM",
				"Nível de Ruído: 23.5 dBA (Max)",
				"Fluxo de Ar: 62 CFM",
				"Pressão Estática: 2.55mm H²O",
				"Tipo de Rolamento: Hydraulic",
				"Tipo de Conexão: Conectores de alimentação: 1* 4-pinos, 12V DC",
				"Peso: 266g",
				"Compatibilidade: Intel{LGA 775/115x/1366}, AMD{AM3/AM4}, TDP < 95W",
			],
			"SPdQ": true,
		},
		"CO_0002": {
			"name": "Cooler - Fan Rise Mode Wind W1 120mm Led Branco - Rm-wn-01-bw",
			"price": 15.82,
			"discount": [8,12,12],
			"image": "CO_0002.png",
			"description": "Ventilador com 9 lâminas. Possui iluminação com 12 LEDS econômicos para o computador. Eficiencia de 1500RPM para a ventilação e resfriamento.",
			"characteristics": [
				"Fluxo de ar do Fan: 50 CFM",
				"Dimensões: 120 x 120 x 25 mm",
				"Nível sonoro: 28 dBA",
				"Velocidade: 1500 Rpm",
				"Conector: 3 pin ou Molex",
			],
			"SPdQ": false,
		},
	},
	"FO": {
		"FO_0000": {
			"name": "Fonte de Alimentacao Cowboy Atx 600w",
			"price": 290.32,
			"discount": [0,0,5],
			"image": "FO_0000.png",
			"description": "Fonte Gamer ATX 600w Cowboy, os cabos possuem capa de proteção.",
			"characteristics": [
				"Número de conectores HDD: 3",
				"Número de conectores SATA: 3",
				"Potência máxima de pico 600 WATTS",
				"MTBD de 100.000 horas 25ºC",
				"Proteção contra curto circuito OVP / OCP SCP",
				"Chaveamento manual 110 / 230V",
				"Ventilador de 120mm ultra silencioso",
				"Cabos com capa de proteção",
			],
			"SPdQ": false,
		},
		"FO_0001": {
			"name": "Fonte de Alimentacao 650w Gp650 Eps 80 Plus Bronze Gamemax",
			"price": 268.99,
			"discount": [2,3,8],
			"image": "FO_0001.png",
			"description": "Fonte de Alimentação 650W GameMax, 2 Eps, 80 Plus Bronza - Gp650",
			"characteristics": [
				"Potência: 650W",
				"Versão: ATX 12V 2.3",
				"Chave Liga/Desliga",
				"Voltagem com seleção automatica (auto range): 100~240V",
				"Frequência: 50~60Hz",
				"Corrente de entrada: 8~4A",
				"Corrente de saída: 3.3V-18A, 5V-20A, +12V-45A, -12V-0.5A, +5VSB-2.5A",
				"Baixo ruído acústico: <20dBA",
				"Proteção interna contra curto circuito: OVP/ SCP/ OPP/ UVP/ OCP",
				"Filtro de entrada AC",
				"PFC Ativo",
			],
			"SPdQ": true,
		},
		"FO_0002": {
			"name": "Fonte ATX Gamer 500w N500 Nyper",
			"price": 165.78,
			"discount": [0,0,5],
			"image": "FO_0002.png",
			"description": "A Fonte Gamer Nyper 500W N500 foi pensada para você, são fontes com diluidor de ruídos e pensada no desempenho do seu PC, e economia de energia. Com mais de 14 anos no mercado de informática, desenvolvemos um produto com alta qualidade, e com excelente custo benefício.",
			"characteristics": [
				"Bivolt: Sim (115v-230v), Manual",
				"Cooler: 12x12cm",
				"Potência: 500W",
				"Conexões: 1 x Alimentação 20 + 4 pinos, 1 x PCI Express 6 pinos, 1 x Auxiliar ATX 4 Pinos, 2 x Conectores IDE, 2 x Conectores de energia SATA",
			],
			"SPdQ": false,
		},
	},
	"GA": {
		"GA_0000": {
			"name": "Gabinete Gamer Brazil Pc Bpc-330atx Preto Lateral Acrílico Sem Fonte",
			"price": 249.99,
			"discount": [0,4,10],
			"image": "GA_0000.png",
			"description": "Gabinete Gamer Brazil Pc Bpc-330atx Preto Lateral Acrílico Sem Fonte.",
			"characteristics": [
				"Lateral em acrílico",
				"Espessura da chapa: 0.5mm",
				"Frente em vidro temperado",
				"Suporta placas ATX e M-ATX",
				"USB: USB*2, USB 3.0*1",
				'BAIAS: 3,5"*1 | 2,5"*2',
				"Slot: 7",
			],
			"SPdQ": true,
		},
		"GA_0001": {
			"name": "Gabinete Atx Brazil Pc Sem Fonte 2x Usb + Áudio",
			"price": 159.99,
			"discount": [15,15,20],
			"image": "GA_0001.png",
			"description": "Desfrute de um produto com design moderno e inovador, unindo o seu gosto com o seu ambiente residencial ou de trabalho. Monte seu computador e deixe seus momentos de lazer ainda melhores com essa novidade.<br/>A Linha de gabinetes Brazil Pc é ideal para quem está atrás do melhor custo x benefício do mercado, o espaço interno é compatível com placas-mãe ATX, micro ATX, com abertura para ventilação lateral, opção de ventilação interna e painel com áudio e USB.",
			"characteristics": [
				"USB I/O: USB + AUDIO; USB 3.0 (Opcional); HDD / SSD:2 * HDD + 2 * SDD",
				"Suporte para placa-mãe: ATX / Micro-ATX",
				"Material e espessura: 0,40 mm SPCC",
				"Slots PCI: 6",
				"Tamanho com painel frontal (C * L * A): 365X175X410mm",
				"Peso: 3,6 kg",
				"Tamanho máximo da CPU: 230x145mm",
			],
			"SPdQ": false,
		},
		"GA_0002": {
			"name": "Gabinete Atx Positivo Horizontal",
			"price": 46.09,
			"discount": [4,4,12],
			"image": "GA_0002.png",
			"description": "Gabinete Atx Positivo Horizontal Sem Fonte - Novo",
			"characteristics": [
				"Tamanho: 10x33x39cm"
			],
			"SPdQ": false,
		},
	},
	"GP": {
		"GP_0000": {
			"name": "PLACA DE VIDEO SAPPHIRE RADEON RX 570 4GB GDDR5 PULSE 256-BIT, 11266-04-20G",
			"price": 679.89,
			"discount": [2,0,9],
			"image": "GP_0000.png",
			"description": "Essa placa é o custo beneficio mais gratificante que alguém pode adquirir, silenciosa, poderosa, linda, roda todos, 'TODOS' os jogos atuais no full sem problemas nenhum, ou seja , melhor impossível, para quem quer um pc de entrada sem gastar muito , ela é um excelente opção , recomendo de mais, e chegou antes do prazo.",
			"characteristics": [
				"Stream Processors: 2048",
				"Impulso Clock do motor 1284 MHz",
				"Memória: 256 bits,GDDR5,1750 MHz,4 GB",
				"Máximo de 5 Saídas: 1x DVI-D, 2x HDMI, 2x Display Port 1.4",
				"Resolução: 3840 x 2160 (120Hz) Pixel resolução DisplayPort, 2560 x 1600 (60 Hz) Pixel Dual Link DVI resolução, 3840 x 2160p (60 Hz) Resolução HDMI",
				"Refrigeração: Ventiladores Dual-X",
				"Dimensões: 230 x 125 x 40 mm",
				"Consumo: < 180w",
				"Sistema Operacional: Windows 10, Windows 7",
			],
			"SPdQ": true,
		},
		"GP_0001": {
			"name": "Placa de Vídeo GPU Aorus RTX 3060 Ti Elite 8G",
			"price": 8185.43,
			"discount": [0,0,10],
			"image": "GP_0001.png",
			"description": "Placa de Vídeo Gigabyte Aorus NVIDIA GeForce RTX 3060 Ti Elite (rev. 2.0) Conceito de design O estilo neonpunk emana na escuridão do brilho de metais de alta qualidade, apresentando uma estética futurista na escuridão da noite. A nova era dos esportes eletrônicos chegou. Sistema de resfriamento WINDFORCE 3X O sistema de resfriamento WINDFORCE 3X possui 3 ventiladores de lâmina exclusivos de 80 mm, rotação alternada, 5 tubos de calor de cobre composto de GPU de toque direto, ventilador ativo 3D e resfriamento de tela, que juntos fornecem dissipação de calor de alta eficiência. O 3D Active Fan fornece resfriamento semipassivo, e os ventiladores permanecerão desligados quando a GPU estiver em um jogo de baixa carga ou baixo consumo de energia. O indicador LED do ventilador pode fornecer uma exibição instantânea do status do ventilador. ",
			"characteristics": [			
				"Processamento de gráficos: GeForce RTX 3060 Ti",
				"Core Clock: 1785 MHz (placa de referência: 1665 MHz)",
				"Clock de memória: 14000 MHz",
				"Tamanho da memória: 8 GB",
				"Tipo de memória: GDDR6",
				"Barramento de memória: 256 bit",
				"Largura de banda da memória (GB / s): 4‎48 GB/s",
				"Barramento da placa: PCI-E 4.0 x 16",
				"Resolução digital máxima: 7680x4320",
				"DirectX: 12 Ultimate",
				"OpenGL: 4.6",
				"Dimensões: 296 x 117 x 56 mm",
				"Conectores de alimentação: 1x 8 pinos + 1x 6 pinos",
				"Saídas: 2x DisplayPort 1.4a, 2x HDMI 2.1'",
				"Peso: 1630 gramas",
			],
			"SPdQ": true,
		},
		"GP_0002": {
			"name": "Placa de Vídeo Asus KO NVIDIA GeForce RTX3070 V2 Gaming",
			"price": 5820.75,
			"discount": [0,0,10],
			"image": "GP_0002.png",
			"description": "ASUS KO GeForce RTX 3070 V2 OC Edition 8 GB GDDR6 com LHR adiciona um toque de elegância à experiência de jogo de última geração NVIDIA Ampere Streaming Multiprocessors Os blocos de construção para a GPU mais rápida e eficiente do mundo, o novo Ampere SM traz 2X a taxa de transferência do FP32 e maior eficiência de energia. Núcleos RT de 2ª geração Experimente 2X a taxa de transferência de núcleos RT de 1ª geração, mais RT e sombreamento simultâneos para um nível totalmente novo de desempenho de rastreamento de raio. Núcleos de tensores de 3ª geração Obtenha até o dobro do rendimento com dispersão estrutural e algoritmos de IA avançados, como DLSS. Agora com suporte para resolução de até 8K, esses núcleos oferecem um grande aumento no desempenho do jogo e recursos de IA totalmente novos. Esta placa de vídeo GeForce RTX 3070 com LHR (taxa de hash leve) oferece taxa de hash ETH de 25 MH/s. Design exclusivo da cobertura Apresenta impressionantes placas frontais de ouro e prata com detalhes RGBA. Projeto do ventilador de tecnologia axial Apresenta um cubo do ventilador menor que facilita as pás mais longas e um anel de barreira que aumenta a pressão do ar para baixo. Capacitores duradouros, duram até 2.5 vezes mais do que o padrão.",
			"characteristics": [
				"Modo OC: 1845 MHz (Boost Clock)",
				"Modo Gaming: 1815 MHz (Boost Clock)",
				"Slot: 2.7",
				"Dimensões: 27,5 x 13,1 x 5,4 cm",
				"Capacidade: 8GB",
				"Tipo: GDDR6",
				"Clock: 14 Gbps",
				"Interface: 256 bits",
				"2x HDMI 2.1 (Nativo)",
				"3x DisplayPort 1.4a (Nativo)",
				"Suporte HDCP 2.3",
				"Resolução digital: 7680 x 4320 (máxima)",
				"Exibição suportada: Até 4x",
				"Suporte NVlink / Crossfire: Não",
				"Potência: 750W *",
				"Conectores de energia: 2x 8 pinos",
			],
			"SPdQ": true,
		},
	},
	"ME": {
		"ME_0000": {
			"name": "Memoria Ram DDR4 - Team Group, T-Force Vulcan 8GB - 2666mhz",
			"price": 204.99,
			"discount": [5,5,15],
			"image": "ME_0000.png",
			"description": "Com o design e a construção de um dissipador de calor com um conceito exterior totalmente novo. Não apenas o design de duas cores é atraente, mas o corte assimétrico também exibe o estilo único da VULCAN.",
			"characteristics": [
				"Tipo de memória: DDR4",
				"Capacidade: 8 GB (1x8GB)",
				"Frequência: 2666 MHz",
				"Latência: CL18-18-18-43",
				"Voltagem: 1.2V",
				"Dissipador de calor: Alumínio",
				"Dimensões: 32 x 140 x 7 mm",
			],
			"SPdQ": true,
		},
		"ME_0001": {
			"name": "Memória Pc De Mesa Xiede Ram Ulo Ddr 184Pin Dimm 400Mhz",
			"price": 76.15,
			"discount": [0,8,13],
			"image": "ME_0001.png",
			"description": "Memória Pc De Mesa Xiede Ram Ulo Ddr 184Pin Dimm 400Mhz",
			"characteristics": [
				"Capacidade: 1GB",
				"Pinos: 184-Pin",
				"Fator de Forma: DIMM,Tecnologia:DDR1 RAM",
				"Compatível com vários sistemas.",
				"Material: PC + metal",
				"Tamanho: 13x3x0,2cm",
				"Velocidade: 400MHz",
				"Especificações da memória: PC-3200",
			],
			"SPdQ": false,
		},
		"ME_0002": {
			"name": "Memoria 8Gb Ddr3 1600 Hyper-X Fury Red Hx316C10Fr/8",
			"price": 512.62,
			"discount": [4,2,6],
			"image": "ME_0002.png",
			"description": "A memória HyperX Fury está disponível nas capacidades de 4GB e 8GB com frequências que variam entre 1333MHz, 1600MHz e 1866MHz. Todas as memórias HyperX Fury possuem o Pcb preto e um dissipador de calor assimétrico, este podendo ser Azul, Preto, Vermelho ou, pela primeira vez, branco. Perfeita para quem procura uma memória de desempenho com um preço acessível, a HyperX Fury é Plug and Play, basta conecta-la que o reconhecimento de sua plataforma host e o overclock é feito automaticamente. Agora cabe a você optar pela HyperX Fury e fazer este upgrade de performance e estilo.",
			"characteristics": [
				"Aplicação: desktop (ambos compatíveis com intel e amd placa-mãe)",
				"Tipo de memória: DDR3",
				"Capacidade de memória: 4gb/8gb",
				"Frequência principal: 1333mhz/1600mhz/1866mhz",
				"Tensão: 1.5v",
				"Número de pinos: 240 pinos",
				"Função: NON-ECC",
			],
			"SPdQ": true,
		},
	},
	"MO": {
		"MO_0000": {
			"name": "Monitor Dell Curvo WQHD 34” S3422DWG Preto",
			"price": 4223.85,
			"discount": [2,5,8],
			"image": "MO_0000.png",
			"description": "Monitor curvo WQHD de 34” que oferece um nível de detalhes extremamente nítido e visão panorâmica, com VESA DisplayHDR 400 e taxa de atualização de 144 Hz que proporciona uma experiência gamer realmente imersiva. Possui design exclusivo com orifícios presentes na parte traseira do monitor, projetados para aumentar a dispersão de calor de modo que você possa jogar o dia inteiro. Além disso, apresenta tecnologia VA, AMD FreeSync Premium e ComfortView.",
			"characteristics": [
				'Tela: 34" WQHD Antirreflexo',
				"Resolução: 3440 x 1440",
				"Taxa de Proporção: 21:9",
				"Tempo de Resposta: 1 ms/ 2 ms",
				"Iluminação: LED",
				"Luminosidade (Brilho): 400 cd/m2",
				"Ângulo de visão (vertical/horizontal): 178°/178°",
				"Conectividade: 2x HDMI 2.0, 1x DisplayPort 1.2, 1x SuperSpeed USB 3.2 Gen1 (5Gbps) upstream port (rear), 2x SuperSpeed USB 3.2 Gen1 (5 Gbps) downstream, 2x SuperSpeed USB 3.2 Gen1 (5 Gbps) downstream), 1x Headphone-out jack",
				"Cabos Inclusos dentro da Caixa: Cabo de alimentação, Cabo DisplayPort, Cabo HDMI, Cabo USB 3.2 upstream de 1a geração (5 Gbit/s)",
				"Diferenciais: Tela WQHD, AMD FreeSyncTM Premium, ComfortView",
				"Compatível com suporte VESA: VESA (100 x 100)",
				"Voltagem: 100 - 240 Volts AC (Bivolt)",
				"Dimensões: 427.31 mm / 527.31mm x 807.90mm x 234.18mm",
				"Peso aproximado: 7.71kg",
			],
			"SPdQ": true,
		},
		"MO_0001": {
			"name": "Monitor 19.5 HQ: Led HDMI ",
			"price": 679.25,
			"discount": [0,0,8],
			"image": "MO_0001.png",
			"description": "A alta definição deste modelo deixará você realizado com imagens vivas e nítidas. Assista vídeos, navegue na internet, jogue, ou execute qualquer outra tarefa com clareza e riqueza de detalhes. A HQ é uma fabricante de telas LED (monitores e televisores) que chegou ao mercado com o compromisso de entregar a seus clientes produtos de alto nível com preço justo. Somos parceiros de grandes fabricantes e hoje os monitores HQ acompanham os computadores das marcas a seguir: EasyPC, 3green, CorPC e FoxPC. Isso só foi possível graças a alta qualidade de nossos produtos. Levando em consideração a inovação tecnológica, todos os nossos monitores vem equipados com conexão HDMI, e isso é um grande diferencial, pois você poderá usufruir das melhores resoluções através desta saída. Controle as configurações da tela de forma intuitiva através dos botões instalados abaixo da tela.",
			"characteristics": [
				'Tamanho da Tela: 19.5"',
				"Resolução Máxima: 1366x768",
				"Contraste: 8000",
				"Conexões: HDMI e VGA",
				"Tempo de Resposta Monitor: 5ms",
				"Ângulo de Visão: 176° x 176°",
				"Brilho: 500cd/m2",
				"Voltagem: Bivolt",
				"Pixel Pitch: 0.255V x 0.55V",
				"Tipo de Monitor: LED Widescreen",
			],
			"SPdQ": false,
		},
		"MO_0002": {
			"name": "Monitor Lcd 15 Quadrado 1024x768 Vga",
			"price": 215.99,
			"discount": [0,0,9],
			"image": "MO_0002.png",
			"description": "O monitor Lcd de 15 polegadas oferece uma imagem surpreendente ao mesmo tempo em que o tamanho compacto não interfere no seu ambiente.com design diferenciado e tecnologias gráficas de alta definição, este monitor entrega toda a tecnologia que você precisa para ter imagens surpreendentes.",
			"characteristics": [
				"Tamanho do tela: 15 polegadas",
				"Tipo de tela: LCD",
				"Resolução da tela: 1024x768p",
				"Conexão do monitor: VGA",
				"Curvo: Não",
				"Cabo: VGA",
			],
			"SPdQ": false,
		},
		"MO_0003": {
			"name": 'Monitor Positivo Wide E2011p LCD 20"',
			"price": 540.59,
			"discount": [1,5,12],
			"image": "MO_0003.png",
			"description": "MONITOR POSITIVO WIDE E2011p LCD 20 POLEGADAS",
			"characteristics": [
				"Tamanho: 20 polegadas",
				"Contraste: 5.000.000:1 DFC",
				"Tempo de resposta: 5 ms",
				"Brilho: 250 cd/m2",
				"Resolução máxima: 1600x900 @ 60 Hz",
				"Pixel Pitch: 0.2766 (H) mm x 0.2766 (V) mm",
				"Ângulo de visão: H: 170° , V: 160°",
				"Freqüência horizontal: 30 ~ 61 kHz",
				"Freqüência vertical: 56 ~ 75 Hz",
				"Revestimento: Anti- Glare, Anti-Reflexiva, Hard Coating",
				"Sinal de video : Analógico - digital",
				"Conectores : DVI / VGA",
				"Base removível",
				"Inclinável : -4~16°",
				"Ajuste de altura : 34,5 até 46 cm",
			],
			"SPdQ": false,
		},
	},
	"PE": {
		"PE_0000": {
			"name": "Mouse Óptico Preto Fosco 1000 Dpi Positivo",
			"price": 14.99,
			"discount": [0,0,3],
			"image": "PE_0000.png",
			"description": "Mouse de fácil configuração que oferece ótima navegabilidade e precisão ao alcance de todos com um custo muito acessível para um mouse óptico. Compatível com Computador PC ou Mac com porta USB.",
			"characteristics": [
				"Interface: USB",
				"Conectividade: Com fio",
				"Número de botões: 3",
				"Sensor: Óptico",
				"Resulução: 1000 DPI",
				"Peso: 106g",
				"Dimensões (C x L x A): 11,7x5,5x3,6cm",
				"Comprimento do Cabo: 170 cm",
			],
			"SPdQ": false,
		},
		"PE_0001": {
			"name": "Mouse sem fio Logitech M170",
			"price": 64.83,
			"discount": [1,0,4],
			"image": "PE_0001.png",
			"description": "Mouse sem fio Logitech M17 O FUTURO É SEM FIO. Com o mouse sem fio Logitech M170, desfrute da confiabilidade de um mouse com fio com a conveniência do sem fio ? graças à tecnologia sem fio Logitech Advanced 2,4 GHz. Este econômico mouse sem fio funciona por 12 meses com uma única pilha AA. Instalação simples: basta conectar o pequeno receptor sem fio à porta USB. Não precisa de pareamento nem instalação de software e o M170 é compatível com Windows, Mac e Chrome?. *A vida útil das pilhas pode variar de acordo com a sua utilização.",
			"characteristics": [
				"Alcance sem fio: 10 metros",
				"Resolução: 1000 DPI",
				"Dimensões: 97.7x61.5x35.2mm",
				"Compatibilidade universal: Windows, Mac, Chrome",
				"Peso: 70.5 gramas",
			],
			"SPdQ": false,
		},
		"PE_0002": {
			"name": "Mouse Gamer Redragon M606 Nothosaur",
			"price": 48.96,
			"discount": [5,5,9],
			"image": "PE_0002.png",
			"description": "O Redragon Nothosaur entrega qualidade e durabilidade para o jogador casual com excelência e acessibilidade sem igual!",
			"characteristics": [
				"Sensor: Pixart de Alta Precisão",
				"Resolução: 3200 DPI",
				"Retroiluminação: LED (4 Cores)",
				"Botão para Troca de DPI: 'On-The-Fly' (4 Velocidades de DPI)",
				"Botões Programáveis: 6",
				"Indicado para Jogos: MOBA",
				"Pegada estilo: Claw e Palm",
				"Dimensões: 7,4cm (L) x 12,7cm (A) x 3,9cm (P) Aprox.",
				"Peso: 251 gramas",
			],
			"SPdQ": true,
		},
		"PE_0003": {
			"name": "Teclado USB Bright 0014 Preto",
			"price": 28.48,
			"discount": [0,0,6],
			"image": "PE_0003.png",
			"description": "Perfeito para as rotinas administrativas.",
			"characteristics": [
				"Conexão: USB",
				"Design simples e eficiente",
				"Padrão: ABNT2",
				"Teclas: 107 (incluíndo 'Ç' e 'Alt Gr')",
				"Cabo: 130cm",
				"Compatibilidade: Windows 98/ME/2000/XP/Vista/7/8/10",
			],
			"SPdQ": false,
		},
		"PE_0004": {
			"name": "Teclado Netbook Positivo Classmate Hmb317da35 br",
			"price": 47.91,
			"discount": [0,0,3],
			"image": "PE_0004.png",
			"description": "Teclado Netbook Positivo Classmate Hmb317da35 br",
			"characteristics": [
				"Padrão: ABNT2",
				"Potência: 5 Watts",
				"Teclas: 67 (incluíndo 'Ç' e 'Alt Gr')",
				"Peso:239g",
			],
			"SPdQ": false,
		},
		"PE_0005": {
			"name": "Teclado Gamer Mancer Necro Rainbow RGB, MCR-NCR-01",
			"price": 98.21,
			"discount": [4,1,20],
			"image": "PE_0005.png",
			"description": "O teclado gamer Necro, foi desenvolvido para além de melhorar a estética do seu setup entregar o desempenho necessário.",
			"characteristics": [
				"- Teclas de atalho multimídia",
				"- Múltiplos efeitos de cores",
				"- fn + ins: Atalho para trocar efeitos",
				"- Padrão: ABNT2",
				"- Iluminação: LED Rainbow",
				"- Quantidade de teclas: 104 teclas (26 anti-ghosting)",
				"- Construção: abs para rigidez e longevidade",
				"- Comprimento do cabo: 1.8 metros",
				"- Peso: 789g",
				"- Dimensões: 467x199x31mm",
			],
			"SPdQ": true,
		},
		"PE_0006": {
			"name": "Fone Headset Office 10 - Bright",
			"price": 34.66,
			"discount": [3,3,10],
			"image": "PE_0006.png",
			"description": "Ótima qualidade de som e captação de voz. A perfeita combinação de microfone e fone de ouvido. Todo o design e mobilidade que você procura. Perfeito para ouvir músicas ou conversar na rede.",
			"characteristics": [
				"Microfone: 6x5 / 58 ±2dB",
				"Impedância: 32 Ohm em 1 KHz",
				"Sensibilidade: 105 dB/mW",
				"Resposta de frequência: 8~22.000Hz",
				"Comprimento do cabo: 1,2m",
				"Plug Estéreo: 3,5mm",
			],
			"SPdQ": false,
		},
		"PE_0007": {
			"name": "Fone Bluetooth Inova FON-6708",
			"price": 78.52,
			"discount": [0,0,10],
			"image": "PE_0007.png",
			"description": "Maximize a sua experiência com o melhor da música. Com um som potente e de qualidade.",
			"characteristics": [
				"Autonomia da bateria: Aproximadamente 6Hrs",
				"Frequência de Resposta: 20HZ a 20Khz",
				"Compatibilidade: PC e mobile",
				"Conexão: Bluetooth e p2",
				"Alcance máximo: 10m",
				"Leitor: Cartão SD",
			],
			"SPdQ": true,
		},
		"PE_0008": {
			"name": "Fone Gamer SY830MV Headset Com microfone, Bass Hd e Led Azul",
			"price": 81.98,
			"discount": [3,0,10],
			"image": "PE_0008.png",
			"description": "Experimente a adrenalina de mergulhar na cena de outra maneira! Ter fones de ouvido específicos para jogos muda completamente sua experiência em cada jogo. O sistema de som surround reforça os graves, equaliza o áudio das vozes recebidas e permite controle das configurações de áudio. O microfone digital omnidirecional é equipado com um algoritmo otimizado, que torna a qualidade de voz impecável, modulação de voz e captura mínima de ruídos externos.",
			"characteristics": [
				"Características estéreo: portátil, som estéreo, redução de ruídos, com microfone",
				"Diâmetro do alto-falante : 40mm/1.57 “(aprox.)",
				"Comprimento do cabo: 2.2m/7.22ft (aprox.)",
				"Fone de ouvido com luz LED",
			],
			"SPdQ": true,
		},
		"PE_0009": {
			"name": "Fone de Ouvido Bluetooth T01 TWS Positivo",
			"price": 125.91,
			"discount": [0,0,12],
			"image": "PE_0009.png",
			"description": "O fone Positivo T01 possui conexão Bluetooth para se conectar a diversos dispositivos, possuindo bateria interna (com carregamento feito através do case de armazenamento), cabo USB para carregamento do case, microfone integrado nos fones, além de possuir uma superfície touch nos mesmos, que permite diversas funções adicionais.",
			"characteristics": [
				"Bateria: 35mA/h",
				"Tempo de recarga: 1:30'",
				"Bateria do case: 300mA/h",
				"Alcance: 10m",
				"Bluetooth: V5.0",
				"Altura: 51mm",
				"Largura: 24mm",
				"Comprimento: 61mm",
				"Peso: 520g",
			],
			"SPdQ": false,
		},
		"PE_000A": {
			"name": "Ouhaobin USB 3.0 HUB Adapter charging Mount Desk: 3USB 3.0, Leitor SD",
			"price": 199.11,
			"discount": [0,1,4],
			"image": "PE_000A.png",
			"description": "Ilhó de mesa com 3 entradas USB e leitor de cartão SD, perfeito para a otimização do espaço.",
			"characteristics": [
				'Tamanho do ilhó: 3"',
				"Dimensões: 69mm(cima)x60mm(baixo)x24mm",
				"USB: 3.0",
				"Entrada de alimentação: Jack J4",
				"Leitor: SD / MMC",
				"Transferência: 5Gb/s",
				"Sistema Plug-and-Play",
			],
			"SPdQ": false,
		},
		"PE_000B": {
			"name": "Adaptador USB 3.0 fêmea/fêmea Yuxi",
			"price": 1.34,
			"discount": [0,0,5],
			"image": "PE_000B.png",
			"description": "Adaptador com duas entradas USB para conectar dois dispositivos com saídas macho.",
			"characteristics": [
				"Dimensões: 40x12x7mm",
				"USB: 3.0",
				"Transferência: 8Gb/s"
			],
			"SPdQ": false,
		},
	},
	"PM": {
		"PM_0000": {
			"name": "Placa Mãe Asus TUF GAMING A520M-PLUS II, AMD AM4, mATX, DDR4 - 90MB17G0-M0EAY0",
			"price": 590.33,
			"discount": [6,7,14],
			"image": "PM_0000.png",
			"description": "Soquete AMD AM4: Pronto para processadores de mesa Ryzen 5000 Series / 4000 G-Series / 3000 Series Desktop Processors. Resfriamento abrangente: Grande dissipador de calor VRM, dissipador de calor PCH, Fan Xpert 2+. Feito para jogos online: tecnologia TUF LANGuard e TurboLAN. Aura Sync RGB: headers RGB integrados e headers Gen 2 endereçáveis ??para tiras de LED RGB, facilmente sincronizados com hardware compatível com Aura Sync.",
			"characteristics": [
				"Processadores AMD Ryzen Série 5000 / Série 5000 G / Série 4000 G / Série 3000 para Desktop",
				"BIOS: 128Mb Flash ROM, UEFI AMI BIOS",
				"Chipset: A520",
				"Memória: 3200 MHz, sem buffer",
				"Gráficos: 1x{DisplayPort 1.2} / 1x{D-Sub} / 1x{HDMI 2.1}",
				"Chipset: AMD A520",
				"Portas SATA: 4x de 6 Gb/s",
				"Ethernet: 1x Realtek Ethernet de 1 Gb",
				"USB traseiro: 4x{Portas USB 3.2 Gen 1 (4x Tipo-A)} / 2x{Portas USB 2.0 (2x Tipo-A)}",
				"USB frontal: 1x{Conector USB 3.2, suporta 2 portas USB 3.2 adicionais} / 2x{Conectores USB 2.0, suportam 4 portas USB 2.0 adicionais}",
				"Suporta: detecção de jack, Multi-streaming, retasking de jack do painel frontal",
				"Suporta reprodução de até 24 bits / 192 kHz",
				"Peso: 1190g",
			],
			"SPdQ": false,
		},
		"PM_0001": {
			"name": "Placa Mãe Biostar A320MH, Chipset A320, AMD AM4, mATX, DDR4",
			"price": 378.89,
			"discount": [2,0,11],
			"image": "PM_0001.png",
			"description": "A série PRO redefine a norma da placa-mãe por aprimoramentos avançados, como o AudioArt Capacitor e o Tough Power Enhanced para transformar o PC em um centro de entretenimento profissional. A nova placa-mãe Series usa o dissipador de calor de revestimento de carbono Nano com melhor efeito de resfriamento em comparação com o dissipador de calor extruturado em alumínio. O material de carbono mesoporoso aumenta a área de dissipação de calor para aumentar a condutividade térmica de forma eficiente e economiza seu custo. Para garantir a longevidade da placa-mãe, as séries PRO com o Tough Power Enhanced podem suportar uma corrente elétrica maciça. Garantir a produção total de energia sem perda de energia adicional, que protege o sistema do seu PC garantindo a durabilidade.",
			"characteristics": [
				"TAMD A-series APU / Ryzen CPU / NPU para Socket AM4",
				"Chipset: AMD A320",
				"Suporte Dual Channel DDR4: 2933/2667/2400/2133/1866 MHz",
				"Suporte Módulos de memória: DIMM não-ECC e ECC Un-buffered",
				"Slot de memória: 2x DDR4 DIMM",
				"Suporte de memória: 32GB",
				"Slots de Expansão: 1x{Slot PCI-E 3.0 x16} / 2x{Slot PCI-E 3.0 x1}",
				"Armazenamento: Suporte SATA3 de 4 x SATA RAID: 0,1,10",
				"Portas USB: 2x{Porta USB 3.1} / 1x{Conector 3.1} / 2x{Porta USB 2.0} / 2x{Conector USB 2.0}",
				"Audio: Realtek ALC887 8-Channel HD Audio",
				"Realtek RTL8111H - 10/100/1000 Controller",
				"Support Super LAN Surge Protection",
				"Dimensões: 22,6x18,4cm",
			],
			"SPdQ": false,
		},
		"PM_0002": {
			"name": "Placa Mãe Amd AM4 Asus Prime B450m-gaming/br DDR4",
			"price": 545.89,
			"discount": [5,3,10],
			"image": "PM_0002.png",
			"description": "Placa-Mãe Asus Prime B450M Gaming/BR AMD DDR4 As placas-mãe ASUS Prime Série B450 fornecem uma base sólida para um sistema eficiente, além de características que satisfazem as suas ambições. Combinamos excelentes recursos integrados nos processadores AMD Ryzen™ com o design e a engenharia essenciais da ASUS, para que você se beneficie das tecnologias líderes do setor, incluindo ajuste automatizado do sistema, controles abrangentes de refrigeração e áudio integrado na placa. Quando você monta um PC com uma placa-mãe ASUS Prime B450M, você monta de maneira inteligente, fácil e econômica. Fan Xpert 2+ Controles flexíveis para máxima refrigeração e silêncio, além de sensor de temperatura GPU para jogos mais refrigerados. Conectividade ultra-rápida Flexibilidade suprema com USB 3.1 Gen 2 e M.2 nativo Header ASUS Aura Sync Conector integrado para fitas de LED RGB, facilmente sincronizado com um portfólio cada vez maior de hardware compatível com Aura Sync 5X Protection III Múltiplas proteções de hardware para proteção geral do sistema DDR4 de até 3466MHz Maior frequência de memória garante mais performance no CPU AMD Ryzen Garanta já a sua Placa-Mãe Asus Prime B450M Gaming/BR AMD DDR4",
			"characteristics": [
				"Processadores: AMD Socket AM4 AMD Ryzen 2ª Geração / Ryzen com Radeon Vega Graphics/Ryzen 1ª Geração / Athlon Radeon Vega Graphics",
				"TDP: 105W",
				"Chipset: AMD B450",
				"Processadores AMD Ryzen 2ª Geração / Ryzen com Radeon Vega Graphics / Athlon™ com Radeon™ Vega Graphics / Ryzen™ 1ª Geração",
				"Arquitetura de memória: Dual Channel",
				"Processador Gráfico Integrado",
				"Múltiplas saídas de vídeo: portas HDMI/DVI-D/D-Sub(VGA)",
				"Resolução máxima de DVI-D: 1920 x 1200 @ 60 Hz",
				"Resolução máxima de HDMI 2.0b: 4096 x 2160 @ 60 Hz",
				"Resolução máxima de D-sub: 1920 x 1200 @ 60 Hz",
				"Chipset AMD B450 : 4x Porta(s) eSATA 6Gb/s, Suporta Raid 0, 1, 10",
				"Áudio: Realtek ALC887 com 8 canais - CODEC de alta definição",
				"Proteção de Áudio: Garante precisão na separação analógica/digital e reduz a maioria das interferências multi-laterais.",
				"Camadas de áudio PCB dedicadas: Camadas separadas para o canal direito e esquerdo para proteger a qualidade dos sinais sensíveis de áudio.",
				"Design iluminado por LED - Ilumine a sua construção com caminhos de áudio iluminados.",
				"Capacitores de áudio premium japoneses: fornecem som natural e imersivo com clareza e fidelidade excepcionais",
				"Sistema Operacional: Windows 10 de 64 bits",
				"Peso: 860g",
			],
			"SPdQ": true,
		},
	},
	"PW": {
		"PW_0000": {
			"name": "Adaptador TP-Link Wireless Dual Band AC1300 Archer T6E PCI Express",
			"price": 499.99,
			"discount": [0,6,9],
			"image": "PW_0000.png",
			"description": "Adaptador TP-Link Wireless Dual Band AC1300 Archer T6E PCI Express",
			"characteristics": [
				"Interface: PCI Express",
				"Tipo de antena: 2 antenas destacáveis da faixa dupla",
				"Frequência: 2.4GHz ou 5GHz",
				"Modos Wireless: Modo Ad-hoc/Infraestrutura",
				"Segurança Wireless: Suporta WEP 64/128 bit , WPA-PSK/WPA2-PSK, 802.1x",
				"Tecnologia de Modulação: DBPSK, DQPSK, CCK, OFDM, 16-QAM, 64-QAM, 256-QAM",
				"Padrão: IEEE 802.11ac/n/a 5GHz / IEEE 802.11b/g/n 2.4GHz",
				"Taxa de Sinal: 867Mbps em 5GHz / 400Mbps em 2.4GHz",
				"Potência de Transmissão:  5GHz{<23dBm (EIRP)} / 2.4GHz{<20dBm (EIRP)}",
				"Wi-Fi: até 1300Mbps (867Mbps na faixa 5GHz ou 400Mpbs na faixa 2.4GHz)",
				"Dual Band: 802.11ac - 3x mais rápido que o padrão 802.11n",
				"Suporta os padrões 802.11 a/b/g/n",
				"Peso: 275g",
			],
			"SPdQ": true,
		},
		"PW_0001": {
			"name": "Adaptador TP-Link PCI Express 300Mbps - TL-WN881ND",
			"price": 109.43,
			"discount": [0,0,5],
			"image": "PW_0001.png",
			"description": "A TP-Link está há mais de 20 anos no mercado, trazendo sempre qualidade para seus clientes. Wi-Fi estável garante entretenimento diário Adaptador PCI Express Wireless N TL-WN881ND permite que você conecte um computador a uma rede wireless e acesso à Internet de alta velocidade. Compatível com IEEE 802.11n, que proporciona velocidade wireless de até 300Mbps, o que é benéfico para o jogo on-line ou streaming de vídeo HD.",
			"characteristics": [
				"Wireless: Frequência: 2.400-2.4835GHz",
				"11n: Até 300Mbps",
				"11g: Até 54Mbps 11b: Até 11Mbps HARDWARE: Interface: PCI Express(x1)",
				"Antena: Omnidirecional, destacável (RP-SMA)",
				"Peso: 215g",
			],
			"SPdQ": false,
		},
		"PW_0002": {
			"name": "Placa de Rede Adaptador Wifi Pci-e 3100mbps 4x4 NitroQAM PCE-AC88 Asus",
			"price": 1074.98,
			"discount": [4,4,14],
			"image": "PW_0002.png",
			"description": "Alguém lê isso?",
			"characteristics": [
				"Desempenho AC final: 1000 + 2167 Mbps",
				"Frequência de operação: 2,4 GHz / 5 GHz",
				"Taxa de transmissão de Wi-Fi (máx.): 2,167 Mbps",
				"Velocidade do Wi-Fi 2,4 GHz: 1 Gbps",
				"Velocidade do Wi-Fi 5 GHz: 2,167 Mbps",
				"Compatibilidade de banda dupla: 2,4 GHz ou 5 GHz",
				"Padrão de rede:- IEEE 802.11a- IEEE 802.11b- IEEE 802.11g- WiFi 4 (802.11n)- WiFi 5 (802.11ac)",
				"Saída de energia: modo b 24dBm / modo ac: 18~21.5dBm / modo g: 22.5~24dBm / modo n: 21~24dBm / modo a/n: 19.5~24dBm",
				"Suporte de sistema operacional: Windows 10 / Windows 7 / WindowsR 10 / WindowsR 7",
			],
			"SPdQ": true,
		},
		"PW_0003": {
			"name": "Roteador Wireless 300Mbps Dir-615 D-Link",
			"price": 99.52,
			"discount": [10,0,10],
			"image": "PW_0003.png",
			"description": "O Dir-615 é Um Roteador Ideal Para Residências E Pequenos Escritórios Que Buscam Um Produto De Qualidade, Confiabilidade, Com Uma Boa Relação Custo-benefício E Desejam Desfrutar De Uma Experiência Wi-fi Segura Para E-mails, Chats, Redes Sociais, Videochamadas, Compartilhar Músicas, Vídeos e Jogos On-line, Entre Outras Atividades.",
			"characteristics": [
				"Velocidade: 300mpbs",
				"Ipv6 Ready: Roteador Wi-fi Pronto Para As Novas Conexões De Internet No Brasil",
				"Entrada: RJ45",
				"Alimentação: Jack J4",
			],
			"SPdQ": false,
		},
		"PW_0004": {
			"name": "Roteador Mercusys 300Mbps - MW301R",
			"price": 85.02,
			"discount": [0,6,12],
			"image": "PW_0004.png",
			"description": "Com suas duas antenas de 5dBi que trabalham para aumentar a sensibilidade de recepção de sinal, o MW301R fornece ampla cobertura wireless.",
			"characteristics": [
				"Botões: Reset",
				"Fonte de Alimentação Externa: 5VDC/0.6A",
				"Antena: 2 x Antenas Fixas omnidirecionais de 5dBi",
				"Padrões Wireless: IEEE 802.11n, IEEE 802.11g, IEEE 802.11b",
				"Frequência: 2.4 - 2.4835GHz",
				"Certificações: CE, ROHS",
				"Potência de Transmissão: <20dBm",
				"Segurança Wireless: 64/128/152-bit WEP / WPA / WPA2,WPA-PSK / WPA2-PSK",
				"Funções Wireless: WDS bridge",
				"Tipo de WAN: IP Dinâmico/IP Estático/PPPoE/PPTP/L2TP",
				"DHCP: Servidor",
				"Redirecionamento de Portas: Virtual server, UPnP, DMZ",
				"DNS Dinâmico: DynDNS、NO-IP",
				"Firewall: Vínculo de Endereço IP e MAC",
				"Protocolos: IPv4",
				"Rede para Convidados: Rede para Convidados 2.4GHz",
				"Dimensões: 135.77 x 93.31 x 25.85mm",
				"Peso: 341g",
			],
			"SPdQ": false,
		},
		"PW_0005": {
			"name": "Roteador Gamer Asus RT-AX82U, 5400Mbps, WiFi6, Aura RGB, AiMesh",
			"price": 1467.11,
			"discount": [2,2,9],
			"image": "PW_0005.png",
			"description": "Desfrute de velocidades ultrarrápidas de até 5400 Mbps com os mais recentes canais WiFi 6 (802.11ax) e 160 MHz. Modo de jogo móvel minimiza o atraso e a latência para jogos móveis com apenas um toque no aplicativo Roteador ASUS. Escolha sua vibração de iluminação para presentar efeitos de iluminação ASUS Aura RGB que você pode escolher entre uma variedade de efeitos de iluminação e personalizar a iluminação para alinhar com modos específicos. Crie uma rede mesh completa e flexível com roteadores compatíveis com AiMesh. Segurança de rede doméstica de nível comercial com ASUS AiProtection Pro gratuito para toda a vida, desenvolvido pela Trend Micro. Possui WPA3 e controles dos pais avançados para proteger sua casa. Desfrute das conexões de jogos WiFi mais rápidas e suaves de sempre com o roteador ASUS RT-AX82U WiFi 6 de banda dupla. Ele oferece WiFi ultrarrápido com velocidades de até 5400 Mbps e vem com tecnologia avançada, incluindo o modo de jogo móvel para uma experiência de jogo móvel de baixa latência e sem atrasos.",
			"characteristics": [
				"Transmitir / Receber: 2,4 GHz 2x2 / 5 GHz 4x4",
				"Processador: Processador tri-core de 1,5 GHz",
				"Memória: 256MB de Flash / 512MB de RAM",
				"Frequência de operação: 2,4GHz / 5GHz",
				"Firewall e controle de acesso: Firewall: Detecção de intrusão SPI, proteção DoS",
				"USB 3.2",
				"Guest Network : 3x 2.4GHz / 3x 5GHz",
				"VPN server: PPTP Server / OpenVPN Server / IPSec server",
				"VPN client: PPTP client / L2TP client / OpenVPN client",
				"Audio: mp3 / wma / wav / pcm / mp4 / lpcm / ogg",
				"Video: asf / avi / divx / mpeg / mpg / ts / vob / wmv / mkv / movce",
				"Support: bt/ nzb/ http/ ed2k",
				"Support encryption/ DHT/ PEX and magnet link",
				"Botões: WPS / Reset / On-Off / LED On-Off",
				"Indicador LED: 1x Alimentação / 2x Wi-Fi / 1x WAN",
				"Fonte de energia: Input[AC]: 110V~240V (50~60Hz) / Output[DC]: 19V, 1.75A",
				"Suporte de sistema operacional: Windows® 10 / Windows® 8 / Windows® 7 / Mac OS X 10.6 / Mac OS X 10.7 / Mac OS X 10.8",
				"Peso: 1570g",
			],
			"SPdQ": true,
		},
	},
	"PR": {
		"PR_0000": {
			"name": "Processador Intel Core i7-9700F Coffee Lake, Cache 12MB, 3.0GHz",
			"price": 1514.35,
			"discount": [4,2,8],
			"image": "PR_0000.png",
			"description": "Os novos processadores Intel Core da 9ª Geração oferecem atualizações de desempenho incríveis para melhorar a produtividade e proporcionar entretenimento surpreendente, otimização de sistema inteligentes e muito mais. Recursos de desempenho inteligente integrados aprendem e se adaptam ao que você faz, direcionando potência dinamicamente para onde ela é mais necessária. Os processadores Intel Core da 9ª Geração fornecem a responsividade para fazer mais. Os processadores Intel Core da 9ª Geração oferecem conectividade cabeada e sem fio rápida, garantida e versátil. Uma nova arquitetura de gráficos oferece suporte a experiências visuais ultravívidas, como vídeo em e jogos. Os processadores Intel Core da 9ª Geração com gráficos Intel permitem experiências de entretenimento nunca vistas. Aproveite jogos incríveis com alto FPS, até mesmo enquanto realiza streaming e gravação. Turbo e aceleração da memória Intel. Em casa ou em qualquer lugar, processadores Intel Core da 9ª Geração capazes de overclocking rodam as plataformas definitivas de jogos em notebooks e desktops.",
			"characteristics": [
				"Litografia: 14 nm",
				"Soquetes suportados: FCLGA1151",
				"Configuração máxima da CPU: 1",
				"Número de núcleos: 8",
				"Nº de threads: 8",
				"Frequência baseada em processador: 3.00 GHz",
				"Frequência turbo max: 4.70 GHz",
				"Cache: 12MB SmartCache",
				"Velocidade do barramento: 8 GT/s DMI3",
				"Tamanho máximo de memória (de acordo com o tipo de memória): 128 GB",
				"Tipos de memória: DDR4-2666",
				"Nº máximo de canais de memória: 2",
				"Largura de banda máxima da memória: 41.6 GB/s",
				"Conjunto de instruções: 64-bit",
				"Peso: 280g",
			],
			"SPdQ": false,
		},
		"PR_0001": {
			"name": "Processador Intel Core i3-10100F, Cache 6MB, 4.30 GHz, LGA 1200",
			"price": 614.06,
			"discount": [5,3,9],
			"image": "PR_0001.png",
			"description": "Processador Intel Core i3-10100F Os novos processadores Intel Core da 10ª Geração oferecem atualizações de desempenho incríveis para melhorar a produtividade e proporcionar entretenimento surpreendente, incluindo até 5,3 GHz, Intel® Wi-Fi 6 (Gig) tecnologia Thunderbolt™ 3, HDR 4K, otimização de sistema inteligentes e muito mais. Produtividade acelerada Recursos de desempenho inteligente integrados aprendem e se adaptam ao que você faz, direcionando potência dinamicamente para onde ela é mais necessária. Os processadores Intel® Core™ da 10ª Geração com memória Intel® Optane™ fornecem a responsividade para fazer mais. A melhor conectividade da categoria1 Com Intel® Wi-Fi 6 (Gig+), conexão Ethernet Intel® I225 e tecnologia Thunderbolt™ 3 integrados, os processadores Intel® Core™ da 10ª Geração oferecem conectividade cabeada e sem fio rápida, garantida e versátil. Entretenimento premium Uma nova arquitetura de gráficos oferece suporte a experiências visuais ultravívidas, como vídeo em HDR 4K e jogos a 1080p. Os processadores Intel® Core™ da 10 ª Geração com gráficos Intel® Iris® Plus permitem experiências de entretenimento nunca vistas. Jogos sérios (serious gaming) Aproveite jogos incríveis com alto FPS, até mesmo enquanto realiza streaming e gravação com até 5,3 GHz. Turbo e aceleração da memória Intel® Optane™. Em casa ou em qualquer lugar, processadores Intel® Core™ da 10ª Geração capazes de overclocking rodam as plataformas definitivas de jogos em notebooks e desktops.",
			"characteristics": [
				"Núcleos: 4",
				"Threads: 8",
				"Frequência: Base{3.60GHz} / Turbo max{4.30GHz}",
				"Cache: 6MB Intel® Smart Cache",
				"Velocidade do barramento: 8GT/s",
				"TDP: 65W",
				"Tamanho máximo de memória (de acordo com o tipo de memória): 128GB",
				"Tipos de memória: DDR4-2666",
				"Nº máximo de canais de memória: 2",
				"Largura de banda máxima da memória: 41.6GB/s",
				"Peso: 285g",
			],
			"SPdQ": true,
		},
		"PR_0002": {
			"name": "Processador Intel Core i9-10900F, Cache 20MB, 2.8GHz (5.2GHz Max Turbo), LGA 1200",
			"price": 3198.02,
			"discount": [0,0,11],
			"image": "PR_0002.png",
			"description": "Recursos de desempenho inteligente integrados aprendem e se adaptam ao que você faz, direcionando potência dinamicamente para onde ela é mais necessária. Os processadores Intel Core da 10a geração com memória Intel Optane fornecem a responsividade para fazer mais.",
			"characteristics": [
				"Litografia: 14 nm",
				"Número de Núcleos: 10",
				"Número de threads: 20",
				"Frequência: Baseada em processador 2.80GHz",
				"Frequência turbo máxima: 5.20GHz",
				"Frequência da Intel Thermal Velocity Boost: 5.20GHz",
				"Cache: 20MB Intel Smart Cache",
				"Velocidade do barramento: 8GT/s",
				"Tecnologia Intel® Turbo Boost Max 3.0 Frequência: 5,10 GHz",
				"TDP: 65W",
				"Tamanho máximo de memória (dependendo do tipo de memória): 128GB",
				"Tipos de Memória: DDR4-2933",
				"Número máximo de canais de memória: 2",
				"Largura de banda máxima da memória: 45.8GB/s",
				"Intel: 64bits",
				"Peso: 330g",
			],
			"SPdQ": true,
		},
	},
}
